spring:
  profiles:
    active: development
  application:
    name: "%APP_NAME%"
    version: "%APP_VERSION%"
    build:
      time: "%APP_BUILD_TIME%"
      os:
        name: "%APP_BUILD_OS_NAME%"
        version: "%APP_BUILD_OS_VERSION%"
      git:
        commit: "%APP_BUILD_GIT_COMMIT%"
        branch: "%APP_BUILD_GIT_BRANCH%"
  cassandra:
    keyspace-name: lulz_ltd_keyspace
    port: 9042
    schema-action: none

---
###############################
### Development environment ###
###############################
spring:
  config:
    activate:
      on-profile: development
  cassandra:
    contact-points: localhost
    local-datacenter: datacenter1
    username: username
    password: password

---
##########################
### Docker environment ###
##########################
spring:
  config:
    activate:
      on-profile: docker
  cassandra:
    contact-points: cassandra
    local-datacenter: datacenter1
    username: username
    password: password

---
###########################
### Staging environment ###
###########################
spring:
  config:
    activate:
      on-profile: staging

---
###########################
### Testing environment ###
###########################
spring:
  config:
    activate:
      on-profile: testing

---
##############################
### Production environment ###
##############################
spring:
  config:
    activate:
      on-profile: production
