spring:
  profiles:
    active: development
  application:
    name: Test
    version: 0.1.2
    build:
      time: 2000-01-01 00:00:00 UTC
      os:
        name: IntegrationTest
        version: 1
      git:
        commit: 00000000
        branch: noTask
